import type { InputKind, Language, PhaseName } from "../../server/research/types";

export const PHASE_LABELS: Record<PhaseName, string> = {
  dossier: "Dossier en marktsituatie",
  bull: "Bull-analist",
  bear: "Bear-analist",
  valuation: "Waardering en Wall Street",
  committee: "Onafhankelijke analist",
  synthesis: "Synthese en dashboard",
  onepager: "One-pager",
};

export const KIND_LABELS: Record<InputKind, string> = {
  stock: "Aandeel",
  etf: "ETF",
  commodity: "Grondstof",
  theme: "Thema",
  sector: "Sector",
};

export const LANGUAGE_LABELS: Record<Language, string> = {
  nl: "Nederlands",
  en: "Engels",
};

/** Teksten van het A4-template in beide rapporttalen. */
export const BRIEF_TEXT = {
  nl: {
    investmentBrief: "Investment brief",
    landscape: "Investeringslandschap",
    independentReview: "Onafhankelijke beoordeling",
    balanceNote: "sterkte van het bewijs, geen koerskans",
    fundamentals: "Fundamentele ontwikkeling",
    actual: "gerealiseerd",
    estimate: "schatting",
    guidance: "guidance",
    valuation: "Intrinsieke waarde per aandeel",
    current: "Koers",
    bear: "Bear",
    base: "Base",
    bull: "Bull",
    analystTargets: "Koersdoelen analisten",
    consensus: "Consensus",
    trend: { rising: "stijgend", stable: "stabiel", falling: "dalend", unknown: "onbekend" },
    bullCase: "Bull-case",
    bearCase: "Bear-case",
    dashboard: "Thesis-dashboard",
    metric: "Indicator",
    strengthens: "These wordt sterker als",
    weakens: "These wordt zwakker als",
    nextCheckpoint: "Volgend ijkmoment",
    coreThesis: "Kernthese",
    conclusion: "Conclusie",
    marketMap: "Marktkaart",
    tactical: "Tactisch / cyclisch",
    structural: "Structureel / lange duur",
    opportunities: "Investeerbare kandidaten",
    ticker: "Ticker",
    exposure: "Exposure",
    price: "Koers",
    target: "Doel",
    upside: "Upside",
    confidence: "Vertrouwen",
    upsideChart: "Upside volgens consensus",
    confidenceChart: "Vertrouwensscore (1-5)",
    watchlist: "Directe assets en niet-aandelen",
    horizon: { structural: "Structureel", cyclical: "Cyclisch", tactical: "Tactisch" },
    footer:
      "Interne analyse, opgesteld met behulp van AI (Claude) op basis van openbare bronnen. Geen beleggingsadvies. Controleer cijfers vóór gebruik.",
    pricesAsOf: "Koersen per",
  },
  en: {
    investmentBrief: "Investment brief",
    landscape: "Investment landscape",
    independentReview: "Independent review",
    balanceNote: "strength of evidence, not price probability",
    fundamentals: "Fundamental trajectory",
    actual: "actual",
    estimate: "estimate",
    guidance: "guidance",
    valuation: "Intrinsic value per share",
    current: "Price",
    bear: "Bear",
    base: "Base",
    bull: "Bull",
    analystTargets: "Analyst price targets",
    consensus: "Consensus",
    trend: { rising: "rising", stable: "stable", falling: "falling", unknown: "unknown" },
    bullCase: "Bull case",
    bearCase: "Bear case",
    dashboard: "Thesis dashboard",
    metric: "Indicator",
    strengthens: "Thesis strengthens if",
    weakens: "Thesis weakens if",
    nextCheckpoint: "Next checkpoint",
    coreThesis: "Core thesis",
    conclusion: "Conclusion",
    marketMap: "Market map",
    tactical: "Tactical / cyclical",
    structural: "Structural / long-duration",
    opportunities: "Investable candidates",
    ticker: "Ticker",
    exposure: "Exposure",
    price: "Price",
    target: "Target",
    upside: "Upside",
    confidence: "Confidence",
    upsideChart: "Street-implied upside",
    confidenceChart: "Confidence score (1-5)",
    watchlist: "Direct assets and non-equity",
    horizon: { structural: "Structural", cyclical: "Cyclical", tactical: "Tactical" },
    footer:
      "Internal analysis prepared with the help of AI (Claude) from public sources. Not investment advice. Verify figures before use.",
    pricesAsOf: "Prices as of",
  },
} as const;

export type BriefText = (typeof BRIEF_TEXT)[Language];
